import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {useState, useEffect} from 'react'

import ModalVisuTask from '../components/modalVisualizartask'
import ModalCreateTask from '../components/modalcreateat'

export default function Home() {
  const [openmodal, setOpenModal] = useState(false)
  const [openmodalCreate, setOpenModalCreate] = useState(false)
  const [task, setTask] = useState([])



  return (
    <div className="body">
      <Head>
        <title>Processo de software</title>
        <meta name="Login MEGA" content="Generated by create next app" />
      </Head>

      <nav id="navBar">
        <img src="DAY_by_DAY.png" alt="DAY by DAY" id="logo" />
      </nav>

      <main className=''>
        <button id="openModal" onClick={()=> setOpenModalCreate(true)}>+ Adicionar atividade</button>


        <ul id="listaDeAtividades">
          <li id="atividade" onClick={()=> setOpenModal(true)}><div className='circle'></div></li>
        </ul>

        {openmodal && <ModalVisuTask setOpenModalVisu={setOpenModal} />}
        {openmodalCreate && <ModalCreateTask setOpenModalCreate={() => setOpenModalCreate(false)}/>}

        <canvas className='line-chart'></canvas>
      </main>
    </div>
  )
}
